server:
  port: 8080
  error:
    include-message: always
spring:
  application:
    name: log-service
  #  data:
  #    mongodb:
  #      database: registerDbMongo
  #      uri: mongodb://localhost:27017/testdb
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/logdb}
